name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test SSH Connection to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}          # EC2 퍼블릭 DNS/IP
          username: ${{ secrets.EC2_USERNAME }}  # EC2 로그인 계정 (예: ubuntu)
          key: ${{ secrets.EC2_PEM_KEY }}        # PEM 개인키
          port: ${{ secrets.PORT }}              # 보통 22
          script: |
            echo "SSH connection successful!"
